// Code generated by protoc-gen-go.
// source: oneone.proto
// DO NOT EDIT!

/*
Package oneone is a generated protocol buffer package.

It is generated from these files:
	oneone.proto

It has these top-level messages:
	Point1
	Point2
*/
package oneone

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Point1 struct {
	A int32 `protobuf:"varint,1,opt,name=a" json:"a,omitempty"`
	B int32 `protobuf:"varint,2,opt,name=b" json:"b,omitempty"`
}

func (m *Point1) Reset()                    { *m = Point1{} }
func (m *Point1) String() string            { return proto.CompactTextString(m) }
func (*Point1) ProtoMessage()               {}
func (*Point1) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Point1) GetA() int32 {
	if m != nil {
		return m.A
	}
	return 0
}

func (m *Point1) GetB() int32 {
	if m != nil {
		return m.B
	}
	return 0
}

type Point2 struct {
	A int32 `protobuf:"varint,1,opt,name=a" json:"a,omitempty"`
	B int32 `protobuf:"varint,2,opt,name=b" json:"b,omitempty"`
}

func (m *Point2) Reset()                    { *m = Point2{} }
func (m *Point2) String() string            { return proto.CompactTextString(m) }
func (*Point2) ProtoMessage()               {}
func (*Point2) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Point2) GetA() int32 {
	if m != nil {
		return m.A
	}
	return 0
}

func (m *Point2) GetB() int32 {
	if m != nil {
		return m.B
	}
	return 0
}

func init() {
	proto.RegisterType((*Point1)(nil), "oneone.Point1")
	proto.RegisterType((*Point2)(nil), "oneone.Point2")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Oneone service

type OneoneClient interface {
	GetFeature(ctx context.Context, in *Point1, opts ...grpc.CallOption) (*Point2, error)
}

type oneoneClient struct {
	cc *grpc.ClientConn
}

func NewOneoneClient(cc *grpc.ClientConn) OneoneClient {
	return &oneoneClient{cc}
}

func (c *oneoneClient) GetFeature(ctx context.Context, in *Point1, opts ...grpc.CallOption) (*Point2, error) {
	out := new(Point2)
	err := grpc.Invoke(ctx, "/oneone.oneone/GetFeature", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Oneone service

type OneoneServer interface {
	GetFeature(context.Context, *Point1) (*Point2, error)
}

func RegisterOneoneServer(s *grpc.Server, srv OneoneServer) {
	s.RegisterService(&_Oneone_serviceDesc, srv)
}

func _Oneone_GetFeature_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Point1)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OneoneServer).GetFeature(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/oneone.oneone/GetFeature",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OneoneServer).GetFeature(ctx, req.(*Point1))
	}
	return interceptor(ctx, in, info, handler)
}

var _Oneone_serviceDesc = grpc.ServiceDesc{
	ServiceName: "oneone.oneone",
	HandlerType: (*OneoneServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFeature",
			Handler:    _Oneone_GetFeature_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "oneone.proto",
}

func init() { proto.RegisterFile("oneone.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 143 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xc9, 0xcf, 0x4b, 0xcd,
	0xcf, 0x4b, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x83, 0xf0, 0x94, 0x54, 0xb8, 0xd8,
	0x02, 0xf2, 0x33, 0xf3, 0x4a, 0x0c, 0x85, 0x78, 0xb8, 0x18, 0x13, 0x25, 0x18, 0x15, 0x18, 0x35,
	0x58, 0x83, 0x18, 0x13, 0x41, 0xbc, 0x24, 0x09, 0x26, 0x08, 0x2f, 0x09, 0xae, 0xca, 0x08, 0x9f,
	0x2a, 0x23, 0x0b, 0x2e, 0xa8, 0xa9, 0x42, 0x7a, 0x5c, 0x5c, 0xee, 0xa9, 0x25, 0x6e, 0xa9, 0x89,
	0x25, 0xa5, 0x45, 0xa9, 0x42, 0x7c, 0x7a, 0x50, 0xab, 0x21, 0x36, 0x49, 0xa1, 0xf2, 0x8d, 0x94,
	0x18, 0x9c, 0x94, 0xb9, 0xc4, 0x33, 0xf3, 0xf5, 0xd2, 0x8b, 0x0a, 0x92, 0xf5, 0x52, 0x2b, 0x12,
	0x73, 0x0b, 0x72, 0x52, 0x8b, 0xa1, 0x6a, 0x9c, 0xa0, 0x46, 0x06, 0x30, 0x26, 0xb1, 0x81, 0x5d,
	0x6e, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0xd0, 0x8d, 0x62, 0x92, 0xc9, 0x00, 0x00, 0x00,
}
