// Code generated by protoc-gen-go.
// source: ping.proto
// DO NOT EDIT!

/*
Package ping is a generated protocol buffer package.

It is generated from these files:
	ping.proto

It has these top-level messages:
	Packet
*/
package ping

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Packet struct {
	Pack []byte `protobuf:"bytes,1,opt,name=pack,proto3" json:"pack,omitempty"`
}

func (m *Packet) Reset()                    { *m = Packet{} }
func (m *Packet) String() string            { return proto.CompactTextString(m) }
func (*Packet) ProtoMessage()               {}
func (*Packet) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Packet) GetPack() []byte {
	if m != nil {
		return m.Pack
	}
	return nil
}

func init() {
	proto.RegisterType((*Packet)(nil), "ping.packet")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Ping service

type PingClient interface {
	Pingpong(ctx context.Context, opts ...grpc.CallOption) (Ping_PingpongClient, error)
}

type pingClient struct {
	cc *grpc.ClientConn
}

func NewPingClient(cc *grpc.ClientConn) PingClient {
	return &pingClient{cc}
}

func (c *pingClient) Pingpong(ctx context.Context, opts ...grpc.CallOption) (Ping_PingpongClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Ping_serviceDesc.Streams[0], c.cc, "/ping.ping/pingpong", opts...)
	if err != nil {
		return nil, err
	}
	x := &pingPingpongClient{stream}
	return x, nil
}

type Ping_PingpongClient interface {
	Send(*Packet) error
	Recv() (*Packet, error)
	grpc.ClientStream
}

type pingPingpongClient struct {
	grpc.ClientStream
}

func (x *pingPingpongClient) Send(m *Packet) error {
	return x.ClientStream.SendMsg(m)
}

func (x *pingPingpongClient) Recv() (*Packet, error) {
	m := new(Packet)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Ping service

type PingServer interface {
	Pingpong(Ping_PingpongServer) error
}

func RegisterPingServer(s *grpc.Server, srv PingServer) {
	s.RegisterService(&_Ping_serviceDesc, srv)
}

func _Ping_Pingpong_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PingServer).Pingpong(&pingPingpongServer{stream})
}

type Ping_PingpongServer interface {
	Send(*Packet) error
	Recv() (*Packet, error)
	grpc.ServerStream
}

type pingPingpongServer struct {
	grpc.ServerStream
}

func (x *pingPingpongServer) Send(m *Packet) error {
	return x.ServerStream.SendMsg(m)
}

func (x *pingPingpongServer) Recv() (*Packet, error) {
	m := new(Packet)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Ping_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ping.ping",
	HandlerType: (*PingServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "pingpong",
			Handler:       _Ping_Pingpong_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "ping.proto",
}

func init() { proto.RegisterFile("ping.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 126 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0xc8, 0xcc, 0x4b,
	0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x01, 0xb1, 0x95, 0x64, 0xb8, 0xd8, 0x0a, 0x12,
	0x93, 0xb3, 0x53, 0x4b, 0x84, 0x84, 0xb8, 0x58, 0x40, 0x2c, 0x09, 0x46, 0x05, 0x46, 0x0d, 0x9e,
	0x20, 0x30, 0xdb, 0xc8, 0x84, 0x0b, 0xac, 0x4a, 0x48, 0x87, 0x8b, 0x03, 0x44, 0x17, 0xe4, 0xe7,
	0xa5, 0x0b, 0xf1, 0xe8, 0x41, 0x0c, 0x01, 0xeb, 0x92, 0x42, 0xe1, 0x29, 0x31, 0x68, 0x30, 0x1a,
	0x30, 0x3a, 0xc9, 0x43, 0x74, 0x39, 0x89, 0x66, 0xe6, 0xeb, 0xa5, 0x17, 0x15, 0x24, 0xeb, 0xa5,
	0x56, 0x24, 0xe6, 0x16, 0xe4, 0xa4, 0x16, 0x83, 0xd5, 0x06, 0x30, 0x26, 0xb1, 0x81, 0x5d, 0x60,
	0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x98, 0x01, 0xc4, 0x26, 0x8f, 0x00, 0x00, 0x00,
}
