// Code generated by protoc-gen-go.
// source: onemany.proto
// DO NOT EDIT!

/*
Package onemany is a generated protocol buffer package.

It is generated from these files:
	onemany.proto

It has these top-level messages:
	Point
	Rect
*/
package onemany

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Point struct {
	A int32 `protobuf:"varint,1,opt,name=a" json:"a,omitempty"`
	B int32 `protobuf:"varint,2,opt,name=b" json:"b,omitempty"`
}

func (m *Point) Reset()                    { *m = Point{} }
func (m *Point) String() string            { return proto.CompactTextString(m) }
func (*Point) ProtoMessage()               {}
func (*Point) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Point) GetA() int32 {
	if m != nil {
		return m.A
	}
	return 0
}

func (m *Point) GetB() int32 {
	if m != nil {
		return m.B
	}
	return 0
}

type Rect struct {
	A int32 `protobuf:"varint,1,opt,name=a" json:"a,omitempty"`
	B int32 `protobuf:"varint,2,opt,name=b" json:"b,omitempty"`
}

func (m *Rect) Reset()                    { *m = Rect{} }
func (m *Rect) String() string            { return proto.CompactTextString(m) }
func (*Rect) ProtoMessage()               {}
func (*Rect) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Rect) GetA() int32 {
	if m != nil {
		return m.A
	}
	return 0
}

func (m *Rect) GetB() int32 {
	if m != nil {
		return m.B
	}
	return 0
}

func init() {
	proto.RegisterType((*Point)(nil), "onemany.Point")
	proto.RegisterType((*Rect)(nil), "onemany.Rect")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Onemany service

type OnemanyClient interface {
	ReturnStream(ctx context.Context, in *Point, opts ...grpc.CallOption) (Onemany_ReturnStreamClient, error)
}

type onemanyClient struct {
	cc *grpc.ClientConn
}

func NewOnemanyClient(cc *grpc.ClientConn) OnemanyClient {
	return &onemanyClient{cc}
}

func (c *onemanyClient) ReturnStream(ctx context.Context, in *Point, opts ...grpc.CallOption) (Onemany_ReturnStreamClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Onemany_serviceDesc.Streams[0], c.cc, "/onemany.onemany/ReturnStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &onemanyReturnStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Onemany_ReturnStreamClient interface {
	Recv() (*Rect, error)
	grpc.ClientStream
}

type onemanyReturnStreamClient struct {
	grpc.ClientStream
}

func (x *onemanyReturnStreamClient) Recv() (*Rect, error) {
	m := new(Rect)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Onemany service

type OnemanyServer interface {
	ReturnStream(*Point, Onemany_ReturnStreamServer) error
}

func RegisterOnemanyServer(s *grpc.Server, srv OnemanyServer) {
	s.RegisterService(&_Onemany_serviceDesc, srv)
}

func _Onemany_ReturnStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Point)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(OnemanyServer).ReturnStream(m, &onemanyReturnStreamServer{stream})
}

type Onemany_ReturnStreamServer interface {
	Send(*Rect) error
	grpc.ServerStream
}

type onemanyReturnStreamServer struct {
	grpc.ServerStream
}

func (x *onemanyReturnStreamServer) Send(m *Rect) error {
	return x.ServerStream.SendMsg(m)
}

var _Onemany_serviceDesc = grpc.ServiceDesc{
	ServiceName: "onemany.onemany",
	HandlerType: (*OnemanyServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReturnStream",
			Handler:       _Onemany_ReturnStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "onemany.proto",
}

func init() { proto.RegisterFile("onemany.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 153 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0xcd, 0xcf, 0x4b, 0xcd,
	0x4d, 0xcc, 0xab, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x87, 0x72, 0x95, 0x94, 0xb9,
	0x58, 0x03, 0xf2, 0x33, 0xf3, 0x4a, 0x84, 0x78, 0xb8, 0x18, 0x13, 0x25, 0x18, 0x15, 0x18, 0x35,
	0x58, 0x83, 0x18, 0x13, 0x41, 0xbc, 0x24, 0x09, 0x26, 0x08, 0x2f, 0x49, 0x49, 0x89, 0x8b, 0x25,
	0x28, 0x35, 0x19, 0xaf, 0x1a, 0x23, 0x1b, 0x2e, 0x98, 0x99, 0x42, 0x86, 0x5c, 0x3c, 0x41, 0xa9,
	0x25, 0xa5, 0x45, 0x79, 0xc1, 0x25, 0x45, 0xa9, 0x89, 0xb9, 0x42, 0x7c, 0x7a, 0x30, 0xcb, 0xc1,
	0x56, 0x49, 0xf1, 0xc2, 0xf9, 0x20, 0x53, 0x95, 0x18, 0x0c, 0x18, 0x9d, 0x54, 0xb9, 0x24, 0x32,
	0xf3, 0xf5, 0xd2, 0x8b, 0x0a, 0x92, 0xf5, 0x52, 0x2b, 0x12, 0x73, 0x0b, 0x72, 0x52, 0x8b, 0x61,
	0x8a, 0x9c, 0x60, 0xe6, 0x06, 0x30, 0x26, 0xb1, 0x81, 0x5d, 0x6f, 0x0c, 0x08, 0x00, 0x00, 0xff,
	0xff, 0x23, 0x9b, 0x7d, 0x03, 0xce, 0x00, 0x00, 0x00,
}
